apiVersion: v1
kind: Service
metadata:
  name: {{ include "javaapp.fullname" . }}
  labels:
    {{- include "javaapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      nodePort: 30001
      protocol: TCP
      name: http
  selector:
    {{- include "javaapp.selectorLabels" . | nindent 4 }}
